---
# tasks file for role-zabbix-server

- name: instalando o repositorio do zabiix
  yum: 
    name: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
    state: present
    disable_gpg_check: yes
  become: yes


- name: instalando pacotes do role-zabbix-server
  yum:
    name:
      - php
      - php-gd
      - gd 
      - gd-devel
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-apache-conf
      - zabbix-sql-scripts
      - zabbix-selinux-policy
      - zabbix-agent
      - mysql-server
      - python3
      - python3-pip
  become: yes


- name: Instalando algumas dependencias do python
  ansible.builtin.pip:
    name:
      - PyMySQL
    
  
- name: criando database
  mysql_db:
    name: "{{ DBname }}"
    collation: utf8_bin
    encoding: utf8
    login_host: localhost
    login_user: root
    login_password: root
  register: db_created

- name: criando user no db
  mysql_user:
    login_host: localhost
    login_user: root
    login_password: root
    name: "{{ DBuser }}"
    password: "{{ DBpassword }}"
    priv: '*.*:ALL'
    state: present
    host: localhost

- name: verificar se o arquivo server.sql existe
  stat:
    path: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
  register: create_sql_gz_exist


- name: unzip arquivo server.sql.gz
  command: gunzip /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
  when: create_sql_gz_exist


- name: importando tables para o db do zabbix
  mysql_db:
    state: import
    login_host: localhost
    login_user: root
    login_password: root
    name: "{{ DBname }}"
    collation: utf8_bin
    encoding: utf8
    target: /usr/share/zabbix-sql-scripts/mysql/server.sql
    
- name: copiando tamplete do zabbix server
  template:
    dest: /etc/zabbix/zabbix-server.conf
    src: zabbix-server.conf

- name: iniciando o zabbix server
  service:
    name: zabbix-server
    enabled: yes
    state: restarted

- name: iniciando o zabbix agent
  service:
    name: zabbix-agent
    enabled: yes
    state: restarted

- name: iniciando httpd
  service:
    name: httpd
    enabled: yes
    state: restarted

- name: iniciando php
  service:
    name: php-fpm
    enabled: yes
    state: restarted
