name: trivy-sbom
on:
  push:
    branches:
    - main
permissions:
  contents: write

jobs:
  scan:
    name: checkout-sbom
    runs-on: ubuntu-20.04
    steps:
      - name: checkout-sbom
        uses: actions/checkout@v3
      
      - name: trivy-sbom
        uses: aquasecurity/trivy-action@master
        with:
          sacn-type: 'fs'
          format: 'github'
          scan-refs: '.'
          outputs: 'dependency-results.sbom.json'
          github-pat: ${{ secrets.GITHUB_TOKEN }}




  
